baseURL = "https://blog.grisge.info/"
languageCode = "en-us"
title = "Blog of Gris"
theme = "m10c"

[params]
author = "Gris Ge <cnfourt@gmail.com>"
description = """
高议而不可及
不如卑论之有功也
Some people dream of success,
while other people get up every morning and make it happen.
"""
avatar = "avatar.png"

[[params.social]]
icon = "github"
name = "github"
url = "https://github.com/cathay4t"

[params.style]
darkColor = "#000000"
darkestColor = "#000000"
lightColor = "#52d052"
lightestColor = "#72ff72"
primaryColor = "#008200"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4
