baseURL = "https://blog.grisge.info/"
languageCode = "en-us"
title = "Blog of Gris"
theme = "m10c"

[params]
author = "Gris Ge <cnfourt@gmail.com>"
description = """
高议而不可及
不如卑论之有功也
Some people dream of success,
while other people get up every morning and make it happen.
"""
avatar = "avatar.png"

[[params.social]]
name = "github"
url = "https://github.com/cathay4t"

[params.style]
darkestColor = "#d35050"
darkColor = "#212121"
primaryColor = "#ffffff"
lightColor = "#a2a2a2"
lightestColor = "#d3d3d3"
